export const activityOptions = [
  { label: "Weight lifting", value: "lifting" },
  // { label: "Fitness", value: "fitness" },
  {
    label: "Outdoor Adventurer",
    value: "Walk/run, playing with children, moderate",
  },
  { label: "Sports Player", value: "Sports Player" },
  { label: "Swimmer", value: "Swimmer" },
  { label: "Cyclist", value: "Cyclist" },
  { label: "Runner", value: "Runner" },
  { label: "Yoga", value: "Yoga" },
  { label: "Dancer", value: "Dancer" },
  { label: "Martial Artist", value: "Martial Artist" },
  { label: "Home Workout", value: "Home Workout" },
  { label: "Walking Enthusiast", value: "Walking Enthusiast" },
  { label: "No Activity", value: "No Activity" },
  { label: "Occasional Activity", value: "Occasional Activity" },
  { label: "Gardener", value: "Gardener" },
  { label: "Active Commuter", value: "Active Commuter" },
  { label: "Parental Activities", value: "Parental Activities" },
  { label: "Recreational Sports", value: "Recreational Sports" },
  { label: "Fitness Class Attendee", value: "Fitness Class Attendee" },
];

export const trainingGoalOptions = [
  "Muscle Gain",
  "Fat Loss",
  "Strength Building",
  "Endurance Training",
  "Flexibility and Mobility",
  "Sport-Specific Training",
  "General Fitness",
  "Weight Maintenance",
  "Injury Rehabilitation",
  "Stress Reduction",
  "Healthy Lifestyle",
  "Other",
];

export const sexOptions = [
  "Male",
  "Female",
  "Non-binary",
  "Transgender Male",
  "Transgender Female",
  "Genderqueer",
  "Genderfluid",
  "Agender",
  "Two-Spirit",
  "Other",
  "Prefer not to say",
];

export const foodAllergyOptions = [
  "None (No Food Allergies)",
  "Dairy",
  "Eggs",
  "Peanuts",
  "Tree Nuts",
  "Soy",
  "Wheat",
  "Fish",
  "Shellfish",
  "Sesame",
  "Gluten",
  "Corn",
  "Lactose",
  "Other",
];

export const trainingPreferenceOptions = [
  "Cardiovascular Training",
  "Strength Training",
  "High-Intensity Interval Training (HIIT)",
  "Yoga/Pilates",
  "CrossFit",
  "Bodyweight Exercises",
  "Weightlifting",
  "Sports-Specific Training",
  "Group Fitness Classes",
  "Outdoor Workouts",
  "Home Workouts",
  "Gym Workouts",
  "Personal Trainer",
  "Online Training",
  "No Preference",
  "Other",
];
