export const activityOptions = [
  "Gym-Goer",
  "Fitness Enthusiast",
  "Outdoor Adventurer",
  "Sports Player",
  "Swimmer",
  "Cyclist",
  "Runner",
  "Yogi",
  "Dancer",
  "Martial Artist",
  "Home Workout",
  "Walking Enthusiast",
  "No Activity",
  "Occasional Activity",
  "Gardener",
  "Active Commuter",
  "Parental Activities",
  "Senior Fitness",
  "Recreational Sports",
  "Fitness Class Attendee",
];

export const trainingGoalOptions = [
  "Muscle Gain",
  "Fat Loss",
  "Strength Building",
  "Endurance Training",
  "Flexibility and Mobility",
  "Sport-Specific Training",
  "General Fitness",
  "Weight Maintenance",
  "Injury Rehabilitation",
  "Stress Reduction",
  "Healthy Lifestyle",
  "Other",
];

export const sexOptions = [
  "Male",
  "Female",
  "Non-binary",
  "Transgender Male",
  "Transgender Female",
  "Genderqueer",
  "Genderfluid",
  "Agender",
  "Two-Spirit",
  "Other",
  "Prefer not to say",
];

export const foodAllergyOptions = [
  "None (No Food Allergies)",
  "Dairy",
  "Eggs",
  "Peanuts",
  "Tree Nuts",
  "Soy",
  "Wheat",
  "Fish",
  "Shellfish",
  "Sesame",
  "Gluten",
  "Corn",
  "Lactose",
  "Other",
];

export const trainingPreferenceOptions = [
  "Cardiovascular Training",
  "Strength Training",
  "High-Intensity Interval Training (HIIT)",
  "Yoga/Pilates",
  "CrossFit",
  "Bodyweight Exercises",
  "Weightlifting",
  "Sports-Specific Training",
  "Group Fitness Classes",
  "Outdoor Workouts",
  "Home Workouts",
  "Gym Workouts",
  "Personal Trainer",
  "Online Training",
  "No Preference",
  "Other",
];
